"""Fix group hierarchy linking

Revision ID: 65683ca951ac
Revises: dc2d6f83d9b2
Create Date: 2025-04-27 14:50:09.007928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65683ca951ac'
down_revision: Union[str, None] = 'dc2d6f83d9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_1_parent_id_fkey', 'groups_1', type_='foreignkey')
    op.drop_column('groups_1', 'parent_id')
    op.drop_constraint('groups_2_parent_id_fkey', 'groups_2', type_='foreignkey')
    op.create_foreign_key(None, 'groups_2', 'groups_1', ['parent_id'], ['id'])
    op.drop_constraint('groups_3_parent_id_fkey', 'groups_3', type_='foreignkey')
    op.create_foreign_key(None, 'groups_3', 'groups_2', ['parent_id'], ['id'])
    op.drop_constraint('groups_4_parent_id_fkey', 'groups_4', type_='foreignkey')
    op.create_foreign_key(None, 'groups_4', 'groups_3', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups_4', type_='foreignkey')
    op.create_foreign_key('groups_4_parent_id_fkey', 'groups_4', 'groups_4', ['parent_id'], ['id'])
    op.drop_constraint(None, 'groups_3', type_='foreignkey')
    op.create_foreign_key('groups_3_parent_id_fkey', 'groups_3', 'groups_4', ['parent_id'], ['id'])
    op.drop_constraint(None, 'groups_2', type_='foreignkey')
    op.create_foreign_key('groups_2_parent_id_fkey', 'groups_2', 'groups_3', ['parent_id'], ['id'])
    op.add_column('groups_1', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('groups_1_parent_id_fkey', 'groups_1', 'groups_2', ['parent_id'], ['id'])
    # ### end Alembic commands ###
